import {
  SwdButton,
  SwdButtonGroup,
  SwdCollapse,
  SwdCollapseItem,
  SwdIcon,
  SwdDropdown,
  SwdDropdownItem,
  SwdTooltip,
  SwdMessage,
  SwdSwitch,
  SwdInput,
  SwdSelect,
  SwdOption,
  SwdForm,
  SwdFormItem,
  SwdAlert,
  SwdNotification,
  SwdLoading,
  SwdUpload,
  SwdPopconfirm,
  SwdMessageBox,
  SwdConfigProvider
} from "@swd-design/components";
import type { Plugin } from "vue";

export default [
  SwdButton,
  SwdButtonGroup,
  SwdCollapse,
  SwdCollapseItem,
  SwdIcon,
  SwdDropdown,
  SwdDropdownItem,
  SwdTooltip,
  SwdMessage,
  SwdInput,
  SwdSwitch,
  SwdSelect,
  SwdOption,
  SwdForm,
  SwdFormItem,
  SwdAlert,
  SwdNotification,
  SwdLoading,
  SwdUpload,
  SwdPopconfirm,
  SwdMessageBox,
  SwdConfigProvider
] as Plugin[];
